// src/pages/AdminDashboard.jsx
import React, { useEffect, useState, useContext } from "react";
import { jsPDF } from "jspdf";
import { AuthContext } from "../context/AuthContext";
import { listApplications, replyToApplication } from "../api/api";
import { useNavigate } from "react-router-dom";

export default function AdminDashboard() {
  const { token, logout } = useContext(AuthContext);
  const navigate = useNavigate();
  const [applications, setApplications] = useState([]);
  const [replyText, setReplyText] = useState({});
  const [statusText, setStatusText] = useState({});
  const [searchTerm, setSearchTerm] = useState("");
  const [filterStatus, setFilterStatus] = useState("All");
  const [sortConfig, setSortConfig] = useState({ key: null, direction: "asc" });

  // Pagination
  const [currentPage, setCurrentPage] = useState(1);
  const pageSize = 10;

  const apiBase = process.env.REACT_APP_API_BASE || "http://localhost:5000";
  const appName = process.env.REACT_APP_NAME || "JobLink Admin Report";
  const logoUrl = process.env.REACT_APP_LOGO_URL || "/logo192.png";
  const brandColor = "#22c55e";

  // Fetch applications
  useEffect(() => {
    if (!token) return navigate("/admin/login");

    const fetchApps = async () => {
      try {
        const res = await listApplications(token);
        setApplications(res.data);
      } catch (err) {
        console.error(err);
        alert("Failed to load applications");
      }
    };

    fetchApps();
  }, [token, navigate]);

  const fileUrl = (filePath) => (filePath ? `${apiBase}/uploads/${filePath}` : "");

  // Reply to application
  const handleReply = async (appId) => {
    try {
      const payload = {
        reply: replyText[appId] || "",
        status: statusText[appId] || "Replied",
      };
      const res = await replyToApplication(appId, payload, token);
      setApplications((prev) =>
        prev.map((app) => (app._id === appId ? res.data : app))
      );
      setReplyText((prev) => ({ ...prev, [appId]: "" }));
      setStatusText((prev) => ({ ...prev, [appId]: "" }));
      alert("Reply sent successfully!");
    } catch (err) {
      console.error(err);
      alert("Failed to send reply.");
    }
  };

  // PDF download (current page)
  const downloadPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const img = new Image();
    img.src = logoUrl;

    img.onload = () => {
      let currentPageNumber = 1;

      const addFooter = () => {
        const totalPages = doc.getNumberOfPages();
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(
          `Generated by ${appName} • Page ${currentPageNumber} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      };

      const drawHeader = () => {
        doc.setFillColor(brandColor);
        doc.rect(0, 0, pageWidth, 40, "F");
        doc.addImage(img, "PNG", 10, 8, 25, 25);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(appName, pageWidth / 2, 20, { align: "center" });
        doc.setFontSize(10);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 40, 28);
        doc.setTextColor(0, 0, 0);
      };

      drawHeader();
      let y = 50;

      const paginatedApps = sortedApplications.slice(
        (currentPage - 1) * pageSize,
        currentPage * pageSize
      );

      paginatedApps.forEach((app, index) => {
        if (index % 2 === 1) {
          doc.setFillColor(245, 245, 245);
          doc.rect(8, y - 8, 194, 65, "F");
        }

        doc.setDrawColor(0);
        doc.setLineWidth(0.5);
        doc.rect(8, y - 8, 194, 65);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text(`Application #${index + 1}`, 10, y);
        y += 7;

        doc.setFont("helvetica", "normal");
        doc.text(`Full Name: ${app.fullname}`, 10, y);
        y += 6;
        doc.text(`Email: ${app.email}`, 10, y);
        y += 6;
        doc.text(`Job Type: ${app.jobType}`, 10, y);
        y += 6;
        doc.text(`Job Position: ${app.jobPosition}`, 10, y);
        y += 6;
        doc.text(`Status: ${app.status || "Pending"}`, 10, y);
        y += 6;
        doc.text(`Reply: ${app.reply || "-"}`, 10, y);
        y += 6;

        if (app.createdAt) {
          const date = new Date(app.createdAt).toLocaleString();
          doc.text(`Submitted: ${date}`, 10, y);
          y += 6;
        }

        if (app.proofFile) {
          doc.setTextColor(0, 0, 255);
          doc.textWithLink("View Proof", 10, y, { url: fileUrl(app.proofFile) });
          y += 6;
        }
        if (app.resumeFile) {
          doc.setTextColor(0, 0, 255);
          doc.textWithLink("View Resume", 10, y, { url: fileUrl(app.resumeFile) });
          y += 6;
        }

        doc.setTextColor(0, 0, 0);
        y += 10;

        if (y > 270) {
          addFooter();
          doc.addPage();
          currentPageNumber++;
          drawHeader();
          y = 50;
        }
      });

      addFooter();
      doc.save("applications_page.pdf");
    };
  };

  // PDF download (all applications)
  const downloadAllPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const img = new Image();
    img.src = logoUrl;

    img.onload = () => {
      let currentPageNumber = 1;

      const addFooter = () => {
        const totalPages = doc.getNumberOfPages();
        doc.setFontSize(9);
        doc.setTextColor(100);
        doc.text(
          `Generated by ${appName} • Page ${currentPageNumber} of ${totalPages}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: "center" }
        );
      };

      const drawHeader = () => {
        doc.setFillColor(brandColor);
        doc.rect(0, 0, pageWidth, 40, "F");
        doc.addImage(img, "PNG", 10, 8, 25, 25);
        doc.setFontSize(18);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(255, 255, 255);
        doc.text(appName, pageWidth / 2, 20, { align: "center" });
        doc.setFontSize(10);
        doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 40, 28);
        doc.setTextColor(0, 0, 0);
      };

      drawHeader();
      let y = 50;

      applications.forEach((app, index) => {
        if (index % 2 === 1) {
          doc.setFillColor(245, 245, 245);
          doc.rect(8, y - 8, 194, 65, "F");
        }

        doc.setDrawColor(0);
        doc.setLineWidth(0.5);
        doc.rect(8, y - 8, 194, 65);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.text(`Application #${index + 1}`, 10, y);
        y += 7;

        doc.setFont("helvetica", "normal");
        doc.text(`Full Name: ${app.fullname}`, 10, y);
        y += 6;
        doc.text(`Email: ${app.email}`, 10, y);
        y += 6;
        doc.text(`Job Type: ${app.jobType}`, 10, y);
        y += 6;
        doc.text(`Job Position: ${app.jobPosition}`, 10, y);
        y += 6;
        doc.text(`Status: ${app.status || "Pending"}`, 10, y);
        y += 6;
        doc.text(`Reply: ${app.reply || "-"}`, 10, y);
        y += 6;

        if (app.createdAt) {
          const date = new Date(app.createdAt).toLocaleString();
          doc.text(`Submitted: ${date}`, 10, y);
          y += 6;
        }

        if (app.proofFile) {
          doc.setTextColor(0, 0, 255);
          doc.textWithLink("View Proof", 10, y, { url: fileUrl(app.proofFile) });
          y += 6;
        }
        if (app.resumeFile) {
          doc.setTextColor(0, 0, 255);
          doc.textWithLink("View Resume", 10, y, { url: fileUrl(app.resumeFile) });
          y += 6;
        }

        doc.setTextColor(0, 0, 0);
        y += 10;

        if (y > 270) {
          addFooter();
          doc.addPage();
          currentPageNumber++;
          drawHeader();
          y = 50;
        }
      });

      addFooter();
      doc.save("all_applications.pdf");
    };
  };

  const pendingCount = applications.filter((app) => !app.reply || !app.status).length;

  const filteredApplications = applications.filter((app) => {
    const search = searchTerm.toLowerCase();
    const matchesSearch =
      app.fullname.toLowerCase().includes(search) ||
      app.email.toLowerCase().includes(search) ||
      app.jobType.toLowerCase().includes(search) ||
      app.jobPosition.toLowerCase().includes(search);

    const status = app.status || "Pending";
    const matchesStatus = filterStatus === "All" || status === filterStatus;

    return matchesSearch && matchesStatus;
  });

  const sortedApplications = [...filteredApplications].sort((a, b) => {
    if (!sortConfig.key) return 0;

    let valA = a[sortConfig.key];
    let valB = b[sortConfig.key];

    if (sortConfig.key === "createdAt") {
      valA = new Date(valA).getTime();
      valB = new Date(valB).getTime();
    } else {
      valA = valA ? valA.toString().toLowerCase() : "";
      valB = valB ? valB.toString().toLowerCase() : "";
    }

    if (valA < valB) return sortConfig.direction === "asc" ? -1 : 1;
    if (valA > valB) return sortConfig.direction === "asc" ? 1 : -1;
    return 0;
  });

  const totalPages = Math.ceil(sortedApplications.length / pageSize);
  const paginatedApplications = sortedApplications.slice(
    (currentPage - 1) * pageSize,
    currentPage * pageSize
  );

  const goToPage = (page) => {
    if (page < 1 || page > totalPages) return;
    setCurrentPage(page);
  };

  return (
    <div className="max-w-6xl mx-auto p-6">
      <h1 className="text-3xl font-bold mb-2 text-center text-gray-800">{appName}</h1>

      {pendingCount > 0 && (
        <p className="text-center text-yellow-700 font-semibold mb-4">
          ⚠️ {pendingCount} applications need attention
        </p>
      )}

      <div className="flex flex-col sm:flex-row justify-between gap-4 mb-4">
        <input
          type="text"
          placeholder="Search by name, email, job type, or position"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="border px-3 py-2 rounded w-full sm:w-1/2"
        />
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className="border px-3 py-2 rounded w-full sm:w-1/4"
        >
          <option value="All">All Status</option>
          <option value="Pending">Pending</option>
          <option value="Replied">Replied</option>
          <option value="Approved">Approved</option>
        </select>
      </div>

      <div className="flex flex-col sm:flex-row justify-between gap-4 mb-6">
        <button
          onClick={() => {
            logout();
            navigate("/admin/login");
          }}
          className="bg-red-500 text-white px-4 py-2 rounded-lg hover:bg-red-600 transition"
        >
          Logout
        </button>

        <button
          onClick={downloadPDF}
          className="bg-green-500 text-white px-4 py-2 rounded-lg hover:bg-green-600 transition"
        >
          Download Current Page
        </button>

        <button
          onClick={downloadAllPDF}
          className="bg-purple-500 text-white px-4 py-2 rounded-lg hover:bg-purple-600 transition"
        >
          Download All Applications
        </button>
      </div>

      {/* Table and Pagination code remains unchanged (use previous code) */}
      {/* ... */}
    </div>
  );
}